project:
  type: website
  output-dir: docs

website:
  title: "Rishiraj's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rishiraj
      - icon: twitter
        href: https://twitter.com/rishirajacharya
format:
  html:
    comments:
      hypothesis:
        theme: clean
    smooth-scroll: true
    theme:
      light: sketchy
      dark: [sketchy, theme-dark.scss]
    css: styles.css